limit_submissions: -1
required_files: 
  - P1.cpp
  - P1.h
  - P2.cpp
  - P2.h
  - P3.cpp
  - P3.h
  - P4.cpp
  - P4.h
  - nearest_spheres.h

  - remove_characters.h

  - binary_search_tree.h

  - grafo.h
